ALTER TABLE "certificates"
ADD COLUMN IF NOT EXISTS "full_name" VARCHAR(200),
ADD COLUMN IF NOT EXISTS "dob" DATE,
ADD COLUMN IF NOT EXISTS "branch" VARCHAR(50),
ADD COLUMN IF NOT EXISTS "graduation_year" INTEGER,
ADD COLUMN IF NOT EXISTS "college_id_link" TEXT;
